version: '3'

services:
  best-friends:
    image: deweiliu/gaokao:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - 80:80
    container_name: gaokao-container